import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'he' | 'en' | 'es' | 'ar';

export const translations = {
  he: {
    dir: "rtl",
    label: "עברית",
    // Landing & General
    heroTitle: "תתאמן כמו אלוף.",
    heroSubtitle: "הצטרף לאלפי מתאמנים שכבר שברו את השיאים של עצמם.",
    ctaStart: "התחל את האתגר ⚽",
    back: "חזרה",
    // Auth
    login: "התחברות",
    loginTitle: "ברוך הבא, אלוף",
    welcomeBack: "ברוך הבא, אלוף",
    emailLabel: "אימייל",
    passwordLabel: "סיסמה",
    loginButton: "התחבר",
    loginBtn: "התחבר",
    noAccount: "חדש ב-FitBarça? צור חשבון",
    signUp: "הרשמה",
    firstName: "שם פרטי",
    lastName: "שם משפחה",
    confirmPassword: "אימות סיסמה",
    createAccount: "צור חשבון",
    forgotPassword: "שכחת סיסמה?",
    alreadyHaveAccount: "יש לך כבר חשבון?",
    loginHere: "התחבר כאן",
    welcomeNew: "התחל את מסע הכושר שלך",
    // Dashboard
    greeting: "שלום, ",
    whatToDo: "מה נעשה היום?",
    cardWorkout: "יומן אימונים",
    cardProfile: "הפרופיל שלי",
    cardChallenges: "מעקב אתגרים",
    cardProgress: "גרף התקדמות",
    // Workout Log
    workoutLog: "יומן אימונים",
    addNewExercise: "הוסף תרגיל חדש",
    exerciseName: "שם התרגיל",
    category: "קטגוריה",
    selectCategory: "בחר קטגוריה",
    addExercise: "הוסף תרגיל",
    finishWorkout: "סיום אימון",
    savingData: "שומר נתונים...",
    noExercisesToSave: "אין תרגילים לשמור",
    exerciseAdded: "התרגיל נוסף בהצלחה!",
    workoutSaved: "האימון נשמר בהצלחה! 💪",
    movedTo: "התרגיל הועבר ל",
    // Progress Graph
    progressGraph: "גרף התקדמות",
    selectExercise: "בחר תרגיל",
    progress: "התקדמות",
    noChange: "ללא שינוי",
    decline: "ירידה",
    noData: "אין נתונים עבור תרגיל זה. סיים אימון כדי לראות את ההתקדמות שלך!",
    weight: "משקל",
    weightKg: 'משקל (ק"ג)',
    // Challenges
    myChallenges: "האתגרים שלי",
    challengeTracker: "מעקב אתגרים",
    createNew: "+ אתגר חדש",
    newChallenge: "אתגר חדש",
    challenge30: "אתגר ה-30",
    challenge60: "אתגר ה-60",
    weekGoal: "יעד שבועי",
    workouts: "אימונים",
    createTitle: "יצירת אתגר חדש",
    inputName: "שם האתגר",
    inputTarget: "יעד אימונים בשבוע",
    step1: "שלב 1: בנה אימון על ידי בחירת תגיות",
    addWorkoutBtn: "הוסף אימון לאתגר +",
    addWorkout: "הוסף אימון לאתגר +",
    saveChallengeBtn: "צור אתגר +",
    submit: "צור אתגר +",
    delete: "מחק",
    deleteChallenge: "מחק אתגר",
    reset: "אפס",
    share: "שתף התקדמות",
    completed: "הושלם!",
    customChallenge: "אתגר מותאם",
    noChallenges: "אין אתגרים פעילים",
    createChallengePrompt: "צור אתגר חדש כדי להתחיל לעקוב אחרי ההתקדמות שלך",
    confirmDelete: "האם אתה בטוח שברצונך למחוק את האתגר הזה? פעולה זו לא ניתנת לביטול.",
    cancel: "ביטול",
    challengeCreated: "האתגר נוצר בהצלחה!",
    challengeDeleted: "האתגר נמחק!",
    // Body Parts
    chest: "חזה",
    triceps: "יד אחורית",
    biceps: "יד קדמית",
    backMuscle: "גב",
    shoulders: "כתפיים",
    legs: "רגליים",
    abs: "בטן",
    pullups: "מתח",
    fullBody: "Full Body",
    aerobic: "אירובי",
    // Features
    features: {
      build: "בנייה אישית",
      track: "מעקב צמוד",
      share: "שתף והצלח"
    },
    ticker: "🔥 יוסי סיים אימון חזה | 🏆 דנה השלימה אתגר | ⚽ עמית הצטרף | 💪 שירה שברה שיא אישי"
  },
  en: {
    dir: "ltr",
    label: "English",
    heroTitle: "Train Like a Champion.",
    heroSubtitle: "Join thousands of athletes who already broke their records.",
    ctaStart: "Start Challenge ⚽",
    back: "Back",
    login: "Login",
    loginTitle: "Welcome Back, Champion",
    welcomeBack: "Welcome back, Champion",
    emailLabel: "Email",
    passwordLabel: "Password",
    loginButton: "Login",
    loginBtn: "Login",
    noAccount: "New to FitBarça? Create an account",
    signUp: "Sign Up",
    firstName: "First Name",
    lastName: "Last Name",
    confirmPassword: "Confirm Password",
    createAccount: "Create Account",
    forgotPassword: "Forgot password?",
    alreadyHaveAccount: "Already have an account?",
    loginHere: "Login here",
    welcomeNew: "Begin your fitness journey",
    greeting: "Hello, ",
    whatToDo: "What are we doing today?",
    cardWorkout: "Workout Diary",
    cardProfile: "My Profile",
    cardChallenges: "Challenge Tracker",
    cardProgress: "Progress Graph",
    workoutLog: "Workout Log",
    addNewExercise: "Add New Exercise",
    exerciseName: "Exercise Name",
    category: "Category",
    selectCategory: "Select Category",
    addExercise: "Add Exercise",
    finishWorkout: "Finish Workout",
    savingData: "Saving data...",
    noExercisesToSave: "No exercises to save",
    exerciseAdded: "Exercise added successfully!",
    workoutSaved: "Workout saved successfully! 💪",
    movedTo: "Exercise moved to",
    progressGraph: "Progress Graph",
    selectExercise: "Select Exercise",
    progress: "Progress",
    noChange: "No Change",
    decline: "Decline",
    noData: "No data for this exercise. Finish a workout to see your progress!",
    weight: "Weight",
    weightKg: "Weight (kg)",
    myChallenges: "My Challenges",
    challengeTracker: "Challenge Tracker",
    createNew: "+ New Challenge",
    newChallenge: "New Challenge",
    challenge30: "The 30 Challenge",
    challenge60: "The 60 Challenge",
    weekGoal: "Weekly Goal",
    workouts: "Workouts",
    createTitle: "Create New Challenge",
    inputName: "Challenge Name",
    inputTarget: "Weekly Workout Target",
    step1: "Step 1: Build workout by selecting tags",
    addWorkoutBtn: "Add Workout +",
    addWorkout: "Add Workout +",
    saveChallengeBtn: "Create Challenge +",
    submit: "Create Challenge +",
    delete: "Delete",
    deleteChallenge: "Delete Challenge",
    reset: "Reset",
    share: "Share Progress",
    completed: "Completed!",
    customChallenge: "Custom Challenge",
    noChallenges: "No active challenges",
    createChallengePrompt: "Create a new challenge to start tracking your progress",
    confirmDelete: "Are you sure you want to delete this challenge? This action cannot be undone.",
    cancel: "Cancel",
    challengeCreated: "Challenge created successfully!",
    challengeDeleted: "Challenge deleted!",
    chest: "Chest",
    triceps: "Triceps",
    biceps: "Biceps",
    backMuscle: "Back",
    shoulders: "Shoulders",
    legs: "Legs",
    abs: "Abs",
    pullups: "Pull-ups",
    fullBody: "Full Body",
    aerobic: "Aerobic",
    features: {
      build: "Custom Build",
      track: "Track Progress",
      share: "Share Success"
    },
    ticker: "🔥 Yossi finished Chest Day | 🏆 Dana completed the challenge | ⚽ Amit joined | 💪 Shira broke a record"
  },
  es: {
    dir: "ltr",
    label: "Español",
    heroTitle: "Entrena como un Campeón.",
    heroSubtitle: "Únete a miles de atletas que ya rompieron sus récords.",
    ctaStart: "Empieza el Reto ⚽",
    back: "Atrás",
    login: "Iniciar Sesión",
    loginTitle: "Bienvenido Campeón",
    welcomeBack: "Bienvenido Campeón",
    emailLabel: "Correo",
    passwordLabel: "Contraseña",
    loginButton: "Entrar",
    loginBtn: "Entrar",
    noAccount: "¿Nuevo en FitBarça? Crear cuenta",
    signUp: "Registrarse",
    firstName: "Nombre",
    lastName: "Apellido",
    confirmPassword: "Confirmar Contraseña",
    createAccount: "Crear Cuenta",
    forgotPassword: "¿Olvidaste tu contraseña?",
    alreadyHaveAccount: "¿Ya tienes cuenta?",
    loginHere: "Inicia sesión aquí",
    welcomeNew: "Comienza tu viaje fitness",
    greeting: "Hola, ",
    whatToDo: "¿Qué hacemos hoy?",
    cardWorkout: "Diario de Ejercicios",
    cardProfile: "Mi Perfil",
    cardChallenges: "Seguimiento de Retos",
    cardProgress: "Gráfico de Progreso",
    workoutLog: "Diario de Ejercicios",
    addNewExercise: "Añadir Nuevo Ejercicio",
    exerciseName: "Nombre del Ejercicio",
    category: "Categoría",
    selectCategory: "Seleccionar Categoría",
    addExercise: "Añadir Ejercicio",
    finishWorkout: "Terminar Entrenamiento",
    savingData: "Guardando datos...",
    noExercisesToSave: "No hay ejercicios para guardar",
    exerciseAdded: "¡Ejercicio añadido!",
    workoutSaved: "¡Entrenamiento guardado! 💪",
    movedTo: "Ejercicio movido a",
    progressGraph: "Gráfico de Progreso",
    selectExercise: "Seleccionar Ejercicio",
    progress: "Progreso",
    noChange: "Sin Cambio",
    decline: "Descenso",
    noData: "No hay datos para este ejercicio. ¡Termina un entrenamiento para ver tu progreso!",
    weight: "Peso",
    weightKg: "Peso (kg)",
    myChallenges: "Mis Retos",
    challengeTracker: "Seguimiento de Retos",
    createNew: "+ Nuevo Reto",
    newChallenge: "Nuevo Reto",
    challenge30: "El Reto de 30",
    challenge60: "El Reto de 60",
    weekGoal: "Meta Semanal",
    workouts: "Entrenamientos",
    createTitle: "Crear Nuevo Reto",
    inputName: "Nombre del Reto",
    inputTarget: "Objetivo Semanal",
    step1: "Paso 1: Elige etiquetas",
    addWorkoutBtn: "Añadir Ejercicio +",
    addWorkout: "Añadir Ejercicio +",
    saveChallengeBtn: "Crear Reto +",
    submit: "Crear Reto +",
    delete: "Eliminar",
    deleteChallenge: "Eliminar Reto",
    reset: "Reiniciar",
    share: "Compartir Progreso",
    completed: "¡Completado!",
    customChallenge: "Reto Personalizado",
    noChallenges: "No hay retos activos",
    createChallengePrompt: "Crea un nuevo reto para empezar a seguir tu progreso",
    confirmDelete: "¿Estás seguro de que quieres eliminar este reto? Esta acción no se puede deshacer.",
    cancel: "Cancelar",
    challengeCreated: "¡Reto creado!",
    challengeDeleted: "¡Reto eliminado!",
    chest: "Pecho",
    triceps: "Tríceps",
    biceps: "Bíceps",
    backMuscle: "Espalda",
    shoulders: "Hombros",
    legs: "Piernas",
    abs: "Abdominales",
    pullups: "Dominadas",
    fullBody: "Cuerpo Completo",
    aerobic: "Aeróbico",
    features: {
      build: "Construcción",
      track: "Seguimiento",
      share: "Compartir"
    },
    ticker: "🔥 Jose terminó Pecho | 🏆 Maria completó el reto | ⚽ Carlos se unió | 💪 Ana rompió récord"
  },
  ar: {
    dir: "rtl",
    label: "العربية",
    heroTitle: "تدرب مثل البطل.",
    heroSubtitle: "انضم إلى الآلاف من الرياضيين الذين حطموا أرقامهم القياسية.",
    ctaStart: "ابدأ التحدي ⚽",
    back: "عودة",
    login: "تسجيل الدخول",
    loginTitle: "مرحباً بك أيها البطل",
    welcomeBack: "مرحباً بك أيها البطل",
    emailLabel: "البريد الإلكتروني",
    passwordLabel: "كلمة المرور",
    loginButton: "دخول",
    loginBtn: "دخول",
    noAccount: "جديد في FitBarça؟ أنشئ حساباً",
    signUp: "إنشاء حساب",
    firstName: "الاسم الأول",
    lastName: "اسم العائلة",
    confirmPassword: "تأكيد كلمة المرور",
    createAccount: "إنشاء حساب",
    forgotPassword: "نسيت كلمة المرور؟",
    alreadyHaveAccount: "لديك حساب بالفعل؟",
    loginHere: "سجل دخولك هنا",
    welcomeNew: "ابدأ رحلتك في اللياقة",
    greeting: "مرحباً, ",
    whatToDo: "ماذا نفعل اليوم؟",
    cardWorkout: "سجل التدريبات",
    cardProfile: "ملفي الشخصي",
    cardChallenges: "متتبع التحديات",
    cardProgress: "رسم التقدم",
    workoutLog: "سجل التدريبات",
    addNewExercise: "إضافة تمرين جديد",
    exerciseName: "اسم التمرين",
    category: "الفئة",
    selectCategory: "اختر فئة",
    addExercise: "إضافة تمرين",
    finishWorkout: "إنهاء التمرين",
    savingData: "جاري الحفظ...",
    noExercisesToSave: "لا توجد تمارين للحفظ",
    exerciseAdded: "تمت إضافة التمرين!",
    workoutSaved: "تم حفظ التمرين بنجاح! 💪",
    movedTo: "تم نقل التمرين إلى",
    progressGraph: "رسم التقدم",
    selectExercise: "اختر تمرين",
    progress: "تقدم",
    noChange: "بدون تغيير",
    decline: "انخفاض",
    noData: "لا توجد بيانات لهذا التمرين. أنهِ تمريناً لرؤية تقدمك!",
    weight: "الوزن",
    weightKg: "الوزن (كجم)",
    myChallenges: "تحدياتي",
    challengeTracker: "متتبع التحديات",
    createNew: "+ تحدي جديد",
    newChallenge: "تحدي جديد",
    challenge30: "تحدي الـ 30",
    challenge60: "تحدي الـ 60",
    weekGoal: "الهدف الأسبوعي",
    workouts: "تدريبات",
    createTitle: "إنشاء تحدي جديد",
    inputName: "اسم التحدي",
    inputTarget: "هدف التدريبات الأسبوعي",
    step1: "الخطوة 1: ابني تدريبك باختيار الوسوم",
    addWorkoutBtn: "أضف تدريب للتحدي +",
    addWorkout: "أضف تدريب للتحدي +",
    saveChallengeBtn: "إنشاء التحدي +",
    submit: "إنشاء التحدي +",
    delete: "حذف",
    deleteChallenge: "حذف التحدي",
    reset: "إعادة تعيين",
    share: "شارك تقدمك",
    completed: "مكتمل!",
    customChallenge: "تحدي مخصص",
    noChallenges: "لا توجد تحديات نشطة",
    createChallengePrompt: "أنشئ تحدياً جديداً لتبدأ تتبع تقدمك",
    confirmDelete: "هل أنت متأكد من حذف هذا التحدي؟ لا يمكن التراجع عن هذا.",
    cancel: "إلغاء",
    challengeCreated: "تم إنشاء التحدي!",
    challengeDeleted: "تم حذف التحدي!",
    chest: "صدر",
    triceps: "عضلة ثلاثية",
    biceps: "عضلة ذراع",
    backMuscle: "ظهر",
    shoulders: "أكتاف",
    legs: "أرجل",
    abs: "بطن",
    pullups: "عقلة",
    fullBody: "كامل الجسم",
    aerobic: "تمارين هوائية",
    features: {
      build: "بناء شخصي",
      track: "تتبع دقيق",
      share: "شارك ونجح"
    },
    ticker: "🔥 يوسف أنهى تمرين الصدر | 🏆 دانا أكملت التحدي | ⚽ أحمد انضم | 💪 سارة حطمت الرقم القياسي"
  }
} as const;

type TranslationKeys = keyof Omit<typeof translations.he, 'features'>;
type FeatureKeys = keyof typeof translations.he.features;

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: TranslationKeys) => string;
  tf: (key: FeatureKeys) => string;
  isRtl: boolean;
  translations: typeof translations;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('fitbarca-language');
    return (saved as Language) || 'he';
  });

  const isRtl = language === 'he' || language === 'ar';

  useEffect(() => {
    document.documentElement.dir = isRtl ? 'rtl' : 'ltr';
    localStorage.setItem('fitbarca-language', language);
  }, [language, isRtl]);

  const t = (key: TranslationKeys): string => {
    const value = translations[language][key];
    if (typeof value === 'string') return value;
    const fallback = translations.he[key];
    return typeof fallback === 'string' ? fallback : key;
  };

  const tf = (key: FeatureKeys): string => {
    return translations[language].features[key] || translations.he.features[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, tf, isRtl, translations }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};


