import React, { createContext, useContext, useState, useEffect, ReactNode } from "react";

export type Language = "he" | "en" | "es" | "ar";

export const translations = {
  he: {
    dir: "rtl",
    label: "עברית",
    // Landing & General
    heroTitle: "תתאמן כמו אלוף.",
    heroSubtitle: "הצטרף לאלפי מתאמנים שכבר שברו את השיאים של עצמם.",
    ctaStart: "התחל את האתגר ⚽",
    back: "חזרה",
    // Auth
    login: "התחברות",
    loginTitle: "ברוך הבא, אלוף",
    welcomeBack: "ברוך הבא, אלוף",
    emailLabel: "אימייל",
    passwordLabel: "סיסמה",
    loginButton: "התחבר",
    loginBtn: "התחבר",
    noAccount: "חדש ב-FitBarça? צור חשבון",
    signUp: "הרשמה",
    firstName: "שם פרטי",
    lastName: "שם משפחה",
    confirmPassword: "אימות סיסמה",
    createAccount: "צור חשבון",
    forgotPassword: "שכחת סיסמה?",
    rememberMe: "זכור אותי",
    alreadyHaveAccount: "יש לך כבר חשבון?",
    loginHere: "התחבר כאן",
    welcomeNew: "התחל את מסע הכושר שלך",
    // Dashboard
    greeting: "שלום, ",
    whatToDo: "מה נעשה היום?",
    cardWorkout: "יומן אימונים",
    cardProfile: "פרופיל אימונים",
    cardChallenges: "מעקב אתגרים",
    cardProgress: "גרף התקדמות",
    // Workout Log
    workoutLog: "יומן אימונים",
    addNewExercise: "הוסף תרגיל חדש",
    exerciseName: "שם התרגיל",
    category: "קטגוריה",
    selectCategory: "בחר קטגוריה",
    addExercise: "הוסף תרגיל",
    finishWorkout: "סיום אימון",
    savingData: "שומר נתונים...",
    noExercisesToSave: "אין תרגילים לשמור",
    noChangesToSave: "אין שינויים לשמור",
    exerciseAdded: "התרגיל נוסף בהצלחה!",
    workoutSaved: "האימון נשמר בהצלחה! 💪",
    errorSavingExercise: "שגיאה בשמירת התרגיל",
    movedTo: "התרגיל הועבר ל",
    // Progress Graph
    progressGraph: "גרף התקדמות",
    selectExercise: "בחר תרגיל",
    progress: "התקדמות",
    noChange: "ללא שינוי",
    decline: "ירידה",
    noData: "אין נתונים עבור תרגיל זה. סיים אימון כדי לראות את ההתקדמות שלך!",
    weight: "משקל",
    weightKg: 'משקל (ק"ג)',
    speed: "מהירות",
    time: "זמן",
    strength: "כוח",
    incline: "שיפוע",
    reps: "חזרות",
    sets: "סטים",
    // Challenges
    myChallenges: "האתגרים שלי",
    challengeTracker: "מעקב אתגרים",
    createNew: "+ אתגר חדש",
    newChallenge: "אתגר חדש",
    challenge30: "אתגר ה-30",
    challenge60: "אתגר ה-60",
    weekGoal: "יעד שבועי",
    workouts: "אימונים",
    createTitle: "יצירת אתגר חדש",
    inputName: "שם האתגר",
    inputTarget: "יעד אימונים בשבוע",
    step1: "שלב 1: בנה אימון על ידי בחירת תגיות",
    addWorkoutBtn: "הוסף אימון לאתגר +",
    addWorkout: "הוסף אימון לאתגר +",
    saveChallengeBtn: "צור אתגר +",
    submit: "צור אתגר +",
    delete: "מחק",
    deleteChallenge: "מחק אתגר",
    reset: "אפס",
    share: "שתף התקדמות",
    completed: "הושלם!",
    customChallenge: "אתגר מותאם",
    noChallenges: "אין אתגרים פעילים",
    createChallengePrompt: "צור אתגר חדש כדי להתחיל לעקוב אחרי ההתקדמות שלך",
    confirmDelete: "האם אתה בטוח שברצונך למחוק את האתגר הזה? פעולה זו לא ניתנת לביטול.",
    cancel: "ביטול",
    challengeCreated: "האתגר נוצר בהצלחה!",
    challengeDeleted: "האתגר נמחק!",
    challengeReset: "האתגר אופס בהצלחה!",
    copiedToClipboard: "הטקסט הועתק ללוח!",
    weeklyTarget: "יעד שבועי",
    weekNumber: "שבוע",
    weekCompleted: "שבוע הושלם!",
    congratulations: "מזל טוב!",
    challengeCompleted: "סיימת את האתגר בהצלחה!",
    resetChallenge: "איפוס האתגר?",
    resetChallengeConfirm: "האם אתה בטוח שברצונך לאפס את האתגר הזה? כל ההתקדמות תימחק.",
    resetBtn: "אפס אתגר",
    // Body Parts
    chest: "חזה",
    triceps: "יד אחורית",
    biceps: "יד קדמית",
    backMuscle: "גב",
    shoulders: "כתפיים",
    legs: "רגליים",
    abs: "בטן",
    pullups: "מתח",
    fullBody: "Full Body",
    aerobic: "אירובי",
    stretch: "מתח",
    // Weekly Setup
    selectDayOfWeek: "1. בנה את תוכנית האימונים שלך:",
    selectMuscleGroups: "2. סמן את קבוצות השרירים לאימון:",
    addToMyWorkouts: "הוסף לאימונים שלי",
    updateWorkout: "עדכן אימון",
    cancelEdit: "ביטול",
    myPlan: "התוכנית שלי:",
    resetAll: "איפוס הכל",
    noWorkoutsYet: "עדיין לא הוספת אימונים. בחר יום ושרירים והוסף לרשימה!",
    day: "יום",
    workoutAdded: "האימון נוסף בהצלחה!",
    workoutUpdated: "האימון עודכן בהצלחה!",
    workoutDeleted: "האימון נמחק",
    allWorkoutsDeleted: "כל האימונים נמחקו",
    continueToNextStep: "המשך לשלב הבא",
    stepOf: "שלב {0} מתוך {1}",
    selectDayAndMuscles: "יש לבחור יום וקבוצות שרירים",
    // Days of week
    sunday: "ראשון",
    monday: "שני",
    tuesday: "שלישי",
    wednesday: "רביעי",
    thursday: "חמישי",
    friday: "שישי",
    saturday: "שבת",
    sunShort: "א",
    monShort: "ב",
    tueShort: "ג",
    wedShort: "ד",
    thuShort: "ה",
    friShort: "ו",
    satShort: "ש",
    // Features
    features: {
      build: "בנייה אישית",
      track: "מעקב צמוד",
      share: "שתף והצלח",
    },
    ticker: "🔥 יוסי סיים אימון חזה | 🏆 דנה השלימה אתגר | ⚽ עמית הצטרף | 💪 שירה שברה שיא אישי",
    // AI Coach
    aiCoachTitle: "מאמן אישי AI",
    aiCoachWelcome: "שלום! אני המאמן האישי שלך. איך אוכל לעזור לך היום?",
    aiCoachPlaceholder: "הקלד הודעה...",
    aiCoachSend: "שלח",
    aiCoachError: "מצטער, משהו השתבש. נסה שוב.",
    cardAiCoach: "מאמן אישי AI",
    dailyLimitReached: "הגעת למגבלה היומית",
    dailyLimitMessage: "הגעת למגבלה של 20 הודעות ביום. נסה שוב מחר!",
    dailyLimit: "מגבלה יומית",
    buildPlanFirst: "יש לבנות תוכנית אימונים תחילה",
    buildPlanGuidance: "בנה את תוכנית האימונים שלך לצפייה בשאר הקטגוריות",
    goHome: "לעמוד הבית",
    placeholder_challenge_standard: "לדוגמה: אתגר ה-30",
    placeholder_challenge_numeric: "לדוגמה: לרוץ 100 ק״מ החודש",
    placeholder_challenge_habit: "לדוגמה: 30 יום ללא סוכר",
    userProfile: "פרטי משתמש",
    profileUpdated: "הפרטים עודכנו בהצלחה",
    emailReadOnly: "לא ניתן לשנות את האימייל",
    saving: "שומר...",
    logout: "התנתקות",
    save: "שמור",
    dailyMotivation: "טיפ יומי",
    dailyTips: "טיפים יומיים",
    noTipsAvailable: "אין טיפים זמינים כרגע",
    readFullArticle: "קרא את המאמר המלא",
    readMore: "קרא עוד",
  },
  en: {
    dir: "ltr",
    label: "English",
    heroTitle: "Train Like a Champion.",
    heroSubtitle: "Join thousands of athletes who already broke their records.",
    ctaStart: "Start Challenge ⚽",
    back: "Back",
    login: "Login",
    loginTitle: "Welcome Back, Champion",
    welcomeBack: "Welcome back, Champion",
    emailLabel: "Email",
    passwordLabel: "Password",
    loginButton: "Login",
    loginBtn: "Login",
    noAccount: "New to FitBarça? Create an account",
    signUp: "Sign Up",
    firstName: "First Name",
    lastName: "Last Name",
    confirmPassword: "Confirm Password",
    createAccount: "Create Account",
    forgotPassword: "Forgot password?",
    rememberMe: "Remember me",
    alreadyHaveAccount: "Already have an account?",
    loginHere: "Login here",
    welcomeNew: "Begin your fitness journey",
    greeting: "Hello, ",
    whatToDo: "What are we doing today?",
    cardWorkout: "Workout Diary",
    cardProfile: "My Profile",
    cardChallenges: "Challenge Tracker",
    cardProgress: "Progress Graph",
    workoutLog: "Workout Log",
    addNewExercise: "Add New Exercise",
    exerciseName: "Exercise Name",
    category: "Category",
    selectCategory: "Select Category",
    addExercise: "Add Exercise",
    finishWorkout: "Finish Workout",
    savingData: "Saving data...",
    noExercisesToSave: "No exercises to save",
    noChangesToSave: "No changes to save",
    exerciseAdded: "Exercise added successfully!",
    workoutSaved: "Workout saved successfully! 💪",
    errorSavingExercise: "Error saving exercise",
    movedTo: "Exercise moved to",
    progressGraph: "Progress Graph",
    selectExercise: "Select Exercise",
    progress: "Progress",
    noChange: "No Change",
    decline: "Decline",
    noData: "No data for this exercise. Finish a workout to see your progress!",
    weight: "Weight",
    weightKg: "Weight (kg)",
    speed: "Speed",
    time: "Time",
    strength: "Strength",
    incline: "Incline",
    reps: "Reps",
    sets: "Sets",
    myChallenges: "My Challenges",
    challengeTracker: "Challenge Tracker",
    createNew: "+ New Challenge",
    newChallenge: "New Challenge",
    challenge30: "The 30 Challenge",
    challenge60: "The 60 Challenge",
    weekGoal: "Weekly Goal",
    workouts: "Workouts",
    createTitle: "Create New Challenge",
    inputName: "Challenge Name",
    inputTarget: "Weekly Workout Target",
    step1: "Step 1: Build workout by selecting tags",
    addWorkoutBtn: "Add Workout +",
    addWorkout: "Add Workout +",
    saveChallengeBtn: "Create Challenge +",
    submit: "Create Challenge +",
    delete: "Delete",
    deleteChallenge: "Delete Challenge",
    reset: "Reset",
    share: "Share Progress",
    completed: "Completed!",
    customChallenge: "Custom Challenge",
    noChallenges: "No active challenges",
    createChallengePrompt: "Create a new challenge to start tracking your progress",
    confirmDelete: "Are you sure you want to delete this challenge? This action cannot be undone.",
    cancel: "Cancel",
    challengeCreated: "Challenge created successfully!",
    challengeDeleted: "Challenge deleted!",
    challengeReset: "Challenge reset successfully!",
    copiedToClipboard: "Text copied to clipboard!",
    weeklyTarget: "Weekly Target",
    weekNumber: "Week",
    weekCompleted: "Week Completed!",
    congratulations: "Congratulations!",
    challengeCompleted: "You completed the challenge!",
    resetChallenge: "Reset Challenge?",
    resetChallengeConfirm: "Are you sure you want to reset this challenge? All progress will be lost.",
    resetBtn: "Reset Challenge",
    chest: "Chest",
    triceps: "Triceps",
    biceps: "Biceps",
    backMuscle: "Back",
    shoulders: "Shoulders",
    legs: "Legs",
    abs: "Abs",
    pullups: "Pull-ups",
    fullBody: "Full Body",
    aerobic: "Aerobic",
    stretch: "Stretch",
    selectDayOfWeek: "1. Select day of the week:",
    selectMuscleGroups: "2. Select muscle groups for workout:",
    addToMyWorkouts: "Add to my workouts",
    updateWorkout: "Update Workout",
    cancelEdit: "Cancel",
    myPlan: "My Plan:",
    resetAll: "Reset All",
    noWorkoutsYet: "No workouts added yet. Select a day and muscles to start!",
    day: "Day",
    workoutAdded: "Workout added successfully!",
    workoutUpdated: "Workout updated successfully!",
    workoutDeleted: "Workout deleted",
    allWorkoutsDeleted: "All workouts deleted",
    continueToNextStep: "Continue to Next Step",
    stepOf: "Step {0} of {1}",
    selectDayAndMuscles: "Please select a day and muscle groups",
    sunday: "Sunday",
    monday: "Monday",
    tuesday: "Tuesday",
    wednesday: "Wednesday",
    thursday: "Thursday",
    friday: "Friday",
    saturday: "Saturday",
    sunShort: "Sun",
    monShort: "Mon",
    tueShort: "Tue",
    wedShort: "Wed",
    thuShort: "Thu",
    friShort: "Fri",
    satShort: "Sat",
    features: {
      build: "Custom Build",
      track: "Track Progress",
      share: "Share Success",
    },
    ticker: "🔥 Yossi finished Chest Day | 🏆 Dana completed the challenge | ⚽ Amit joined | 💪 Shira broke a record",
    // AI Coach
    aiCoachTitle: "AI Personal Coach",
    aiCoachWelcome: "Hello! I'm your personal coach. How can I help you today?",
    aiCoachPlaceholder: "Type a message...",
    aiCoachSend: "Send",
    aiCoachError: "Sorry, something went wrong. Please try again.",
    cardAiCoach: "AI Personal Coach",
    dailyLimitReached: "Daily Limit Reached",
    dailyLimitMessage: "You have reached your daily limit of 20 messages. Try again tomorrow!",
    dailyLimit: "Daily Limit",
    buildPlanFirst: "Please build a training plan first",
    buildPlanGuidance: "Build your training plan to access the other categories",
    goHome: "Go Home",
    placeholder_challenge_standard: "Example: 30-Day Challenge",
    placeholder_challenge_numeric: "Example: Run 100km this month",
    placeholder_challenge_habit: "Example: 30 Days No Sugar",
    userProfile: "User Profile",
    profileUpdated: "Profile updated successfully",
    emailReadOnly: "Email cannot be changed",
    saving: "Saving...",
    logout: "Logout",
    save: "Save",
    dailyMotivation: "Daily Tip",
    dailyTips: "Daily Tips",
    noTipsAvailable: "No tips available at the moment",
    readFullArticle: "Read full article",
    readMore: "Read More",
  },
  es: {
    dir: "ltr",
    label: "Español",
    heroTitle: "Entrena como un Campeón.",
    heroSubtitle: "Únete a miles de atletas que ya rompieron sus récords.",
    ctaStart: "Empieza el Reto ⚽",
    back: "Atrás",
    login: "Iniciar Sesión",
    loginTitle: "Bienvenido Campeón",
    welcomeBack: "Bienvenido Campeón",
    emailLabel: "Correo",
    passwordLabel: "Contraseña",
    loginButton: "Entrar",
    loginBtn: "Entrar",
    noAccount: "¿Nuevo en FitBarça? Crear cuenta",
    signUp: "Registrarse",
    firstName: "Nombre",
    lastName: "Apellido",
    confirmPassword: "Confirmar Contraseña",
    createAccount: "Crear Cuenta",
    forgotPassword: "¿Olvidaste tu contraseña?",
    rememberMe: "Recuérdame",
    alreadyHaveAccount: "¿Ya tienes cuenta?",
    loginHere: "Inicia sesión aquí",
    welcomeNew: "Comienza tu viaje fitness",
    greeting: "Hola, ",
    whatToDo: "¿Qué hacemos hoy?",
    cardWorkout: "Diario de Ejercicios",
    cardProfile: "Mi Perfil",
    cardChallenges: "Seguimiento de Retos",
    cardProgress: "Gráfico de Progreso",
    workoutLog: "Diario de Ejercicios",
    addNewExercise: "Añadir Nuevo Ejercicio",
    exerciseName: "Nombre del Ejercicio",
    category: "Categoría",
    selectCategory: "Seleccionar Categoría",
    addExercise: "Añadir Ejercicio",
    finishWorkout: "Terminar Entrenamiento",
    savingData: "Guardando datos...",
    noExercisesToSave: "No hay ejercicios para guardar",
    noChangesToSave: "No hay cambios para guardar",
    exerciseAdded: "¡Ejercicio añadido!",
    workoutSaved: "¡Entrenamiento guardado! 💪",
    errorSavingExercise: "Error al guardar el ejercicio",
    movedTo: "Ejercicio movido a",
    progressGraph: "Gráfico de Progreso",
    selectExercise: "Seleccionar Ejercicio",
    progress: "Progreso",
    noChange: "Sin Cambio",
    decline: "Descenso",
    noData: "No hay datos para este ejercicio. ¡Termina un entrenamiento para ver tu progreso!",
    weight: "Peso",
    weightKg: "Peso (kg)",
    speed: "Velocidad",
    time: "Tiempo",
    strength: "Fuerza",
    incline: "Inclinación",
    reps: "Repeticiones",
    sets: "Series",
    myChallenges: "Mis Retos",
    challengeTracker: "Seguimiento de Retos",
    createNew: "+ Nuevo Reto",
    newChallenge: "Nuevo Reto",
    challenge30: "El Reto de 30",
    challenge60: "El Reto de 60",
    weekGoal: "Meta Semanal",
    workouts: "Entrenamientos",
    createTitle: "Crear Nuevo Reto",
    inputName: "Nombre del Reto",
    inputTarget: "Objetivo Semanal",
    step1: "Paso 1: Elige etiquetas",
    addWorkoutBtn: "Añadir Ejercicio +",
    addWorkout: "Añadir Ejercicio +",
    saveChallengeBtn: "Crear Reto +",
    submit: "Crear Reto +",
    delete: "Eliminar",
    deleteChallenge: "Eliminar Reto",
    reset: "Reiniciar",
    share: "Compartir Progreso",
    completed: "¡Completado!",
    customChallenge: "Reto Personalizado",
    noChallenges: "No hay retos activos",
    createChallengePrompt: "Crea un nuevo reto para empezar a seguir tu progreso",
    confirmDelete: "¿Estás seguro de que quieres eliminar este reto? Esta acción no se puede deshacer.",
    cancel: "Cancelar",
    challengeCreated: "¡Reto creado!",
    challengeDeleted: "¡Reto eliminado!",
    challengeReset: "¡Reto reiniciado!",
    copiedToClipboard: "¡Texto copiado!",
    weeklyTarget: "Objetivo Semanal",
    weekNumber: "Semana",
    weekCompleted: "¡Semana Completada!",
    congratulations: "¡Felicidades!",
    challengeCompleted: "¡Completaste el reto!",
    resetChallenge: "¿Reiniciar Reto?",
    resetChallengeConfirm: "¿Estás seguro de reiniciar este reto? Se perderá todo el progreso.",
    resetBtn: "Reiniciar Reto",
    chest: "Pecho",
    triceps: "Tríceps",
    biceps: "Bíceps",
    backMuscle: "Espalda",
    shoulders: "Hombros",
    legs: "Piernas",
    abs: "Abdominales",
    pullups: "Dominadas",
    fullBody: "Cuerpo Completo",
    aerobic: "Aeróbico",
    stretch: "Estiramiento",
    selectDayOfWeek: "1. Selecciona el día de la semana:",
    selectMuscleGroups: "2. Selecciona grupos musculares:",
    addToMyWorkouts: "Añadir a mis entrenamientos",
    updateWorkout: "Actualizar Entrenamiento",
    cancelEdit: "Cancelar",
    myPlan: "Mi Plan:",
    resetAll: "Reiniciar Todo",
    noWorkoutsYet: "Aún no hay entrenamientos. ¡Selecciona un día y músculos para empezar!",
    day: "Día",
    workoutAdded: "¡Entrenamiento añadido!",
    workoutUpdated: "¡Entrenamiento actualizado!",
    workoutDeleted: "Entrenamiento eliminado",
    allWorkoutsDeleted: "Todos los entrenamientos eliminados",
    continueToNextStep: "Continuar al Siguiente Paso",
    stepOf: "Paso {0} de {1}",
    selectDayAndMuscles: "Selecciona un día y grupos musculares",
    sunday: "Domingo",
    monday: "Lunes",
    tuesday: "Martes",
    wednesday: "Miércoles",
    thursday: "Jueves",
    friday: "Viernes",
    saturday: "Sábado",
    sunShort: "Dom",
    monShort: "Lun",
    tueShort: "Mar",
    wedShort: "Mié",
    thuShort: "Jue",
    friShort: "Vie",
    satShort: "Sáb",
    features: {
      build: "Construcción",
      track: "Seguimiento",
      share: "Compartir",
    },
    ticker: "🔥 Jose terminó Pecho | 🏆 Maria completó el reto | ⚽ Carlos se unió | 💪 Ana rompió récord",
    // AI Coach
    aiCoachTitle: "Entrenador IA",
    aiCoachWelcome: "¡Hola! Soy tu entrenador personal. ¿Cómo puedo ayudarte hoy?",
    aiCoachPlaceholder: "Escribe un mensaje...",
    aiCoachSend: "Enviar",
    aiCoachError: "Lo siento, algo salió mal. Por favor, inténtalo de nuevo.",
    cardAiCoach: "Entrenador IA",
    dailyLimitReached: "Límite Diario Alcanzado",
    dailyLimitMessage: "Has alcanzado tu límite de 20 mensajes diarios. ¡Inténtalo mañana!",
    dailyLimit: "Límite Diario",
    buildPlanFirst: "Por favor, crea un plan de entrenamiento primero",
    buildPlanGuidance: "Crea tu plan de entrenamiento para acceder a otras categorías",
    goHome: "Ir al Inicio",
    placeholder_challenge_standard: "Ejemplo: Desafío de 30 días",
    placeholder_challenge_numeric: "Ejemplo: Correr 100km este mes",
    placeholder_challenge_habit: "Ejemplo: 30 días sin azúcar",
    userProfile: "Perfil de Usuario",
    profileUpdated: "Perfil actualizado exitosamente",
    emailReadOnly: "El email no puede ser cambiado",
    saving: "Guardando...",
    logout: "Cerrar sesión",
    save: "Guardar",
    dailyMotivation: "Consejo del Día",
    dailyTips: "Consejos Diarios",
    noTipsAvailable: "No hay consejos disponibles por el momento",
    readFullArticle: "Leer artículo completo",
    readMore: "Leer Más",
  },
  ar: {
    dir: "rtl",
    label: "العربية",
    heroTitle: "تدرب مثل البطل.",
    heroSubtitle: "انضم إلى الآلاف من الرياضيين الذين حطموا أرقامهم القياسية.",
    ctaStart: "ابدأ التحدي ⚽",
    back: "عودة",
    login: "تسجيل الدخول",
    loginTitle: "مرحباً بك أيها البطل",
    welcomeBack: "مرحباً بك أيها البطل",
    emailLabel: "البريد الإلكتروني",
    passwordLabel: "كلمة المرور",
    loginButton: "دخول",
    loginBtn: "دخول",
    noAccount: "جديد في FitBarça؟ أنشئ حساباً",
    signUp: "إنشاء حساب",
    firstName: "الاسم الأول",
    lastName: "اسم العائلة",
    confirmPassword: "تأكيد كلمة المرور",
    createAccount: "إنشاء حساب",
    forgotPassword: "نسيت كلمة المرور؟",
    rememberMe: "تذكرني",
    alreadyHaveAccount: "لديك حساب بالفعل؟",
    loginHere: "سجل دخولك هنا",
    welcomeNew: "ابدأ رحلتك في اللياقة",
    greeting: "مرحباً, ",
    whatToDo: "ماذا نفعل اليوم؟",
    cardWorkout: "سجل التدريبات",
    cardProfile: "ملفي الشخصي",
    cardChallenges: "متتبع التحديات",
    cardProgress: "رسم التقدم",
    workoutLog: "سجل التدريبات",
    addNewExercise: "إضافة تمرين جديد",
    exerciseName: "اسم التمرين",
    category: "الفئة",
    selectCategory: "اختر فئة",
    addExercise: "إضافة تمرين",
    finishWorkout: "إنهاء التمرين",
    savingData: "جاري الحفظ...",
    noExercisesToSave: "لا توجد تمارين للحفظ",
    exerciseAdded: "تمت إضافة التمرين!",
    workoutSaved: "تم حفظ التمرين بنجاح! 💪",
    errorSavingExercise: "خطأ في حفظ التمرين",
    movedTo: "تم نقل التمرين إلى",
    progressGraph: "رسم التقدم",
    selectExercise: "اختر تمرين",
    progress: "تقدم",
    noChange: "بدون تغيير",
    decline: "انخفاض",
    noData: "لا توجد بيانات لهذا التمرين. أنهِ تمريناً لرؤية تقدمك!",
    weight: "الوزن",
    weightKg: "الوزن (كجم)",
    speed: "السرعة",
    time: "الوقت",
    strength: "القوة",
    incline: "الميل",
    reps: "التكرارات",
    sets: "المجموعات",
    myChallenges: "تحدياتي",
    challengeTracker: "متتبع التحديات",
    createNew: "+ تحدي جديد",
    newChallenge: "تحدي جديد",
    challenge30: "تحدي الـ 30",
    challenge60: "تحدي الـ 60",
    weekGoal: "الهدف الأسبوعي",
    workouts: "تدريبات",
    createTitle: "إنشاء تحدي جديد",
    inputName: "اسم التحدي",
    inputTarget: "هدف التدريبات الأسبوعي",
    step1: "الخطوة 1: ابني تدريبك باختيار الوسوم",
    addWorkoutBtn: "أضف تدريب للتحدي +",
    addWorkout: "أضف تدريب للتحدي +",
    saveChallengeBtn: "إنشاء التحدي +",
    submit: "إنشاء التحدي +",
    delete: "حذف",
    deleteChallenge: "حذف التحدي",
    reset: "إعادة تعيين",
    share: "شارك تقدمك",
    completed: "مكتمل!",
    customChallenge: "تحدي مخصص",
    noChallenges: "لا توجد تحديات نشطة",
    createChallengePrompt: "أنشئ تحدياً جديداً لتبدأ تتبع تقدمك",
    confirmDelete: "هل أنت متأكد من حذف هذا التحدي؟ لا يمكن التراجع عن هذا.",
    cancel: "إلغاء",
    challengeCreated: "تم إنشاء التحدي!",
    challengeDeleted: "تم حذف التحدي!",
    challengeReset: "تم إعادة تعيين التحدي!",
    copiedToClipboard: "تم نسخ النص!",
    weeklyTarget: "الهدف الأسبوعي",
    weekNumber: "أسبوع",
    weekCompleted: "الأسبوع مكتمل!",
    congratulations: "تهانينا!",
    challengeCompleted: "أكملت التحدي!",
    resetChallenge: "إعادة تعيين التحدي؟",
    resetChallengeConfirm: "هل أنت متأكد من إعادة تعيين هذا التحدي؟ سيتم فقدان كل التقدم.",
    resetBtn: "إعادة تعيين",
    chest: "صدر",
    triceps: "عضلة ثلاثية",
    biceps: "عضلة ذراع",
    backMuscle: "ظهر",
    shoulders: "أكتاف",
    legs: "أرجل",
    abs: "بطن",
    pullups: "عقلة",
    fullBody: "كامل الجسم",
    aerobic: "تمارين هوائية",
    stretch: "تمدد",
    selectDayOfWeek: "1. اختر يوم الأسبوع:",
    selectMuscleGroups: "2. اختر مجموعات العضلات:",
    addToMyWorkouts: "أضف إلى تماريني",
    updateWorkout: "تحديث التمرين",
    cancelEdit: "إلغاء",
    myPlan: "خطتي:",
    resetAll: "إعادة تعيين الكل",
    noWorkoutsYet: "لم تضف تمارين بعد. اختر يوماً وعضلات للبدء!",
    day: "يوم",
    workoutAdded: "تمت إضافة التمرين!",
    workoutUpdated: "تم تحديث التمرين!",
    workoutDeleted: "تم حذف التمرين",
    allWorkoutsDeleted: "تم حذف جميع التمارين",
    continueToNextStep: "متابعة للخطوة التالية",
    stepOf: "الخطوة {0} من {1}",
    selectDayAndMuscles: "يرجى اختيار يوم ومجموعات عضلية",
    sunday: "الأحد",
    monday: "الاثنين",
    tuesday: "الثلاثاء",
    wednesday: "الأربعاء",
    thursday: "الخميس",
    friday: "الجمعة",
    saturday: "السبت",
    sunShort: "أحد",
    monShort: "اثن",
    tueShort: "ثلا",
    wedShort: "أرب",
    thuShort: "خمي",
    friShort: "جمع",
    satShort: "سبت",
    features: {
      build: "بناء شخصي",
      track: "تتبع دقيق",
      share: "شارك ونجح",
    },
    ticker: "🔥 يوسف أنهى تمرين الصدر | 🏆 دانا أكملت التحدي | ⚽ أحمد انضم | 💪 سارة حطمت الرقم القياسي",
    // AI Coach
    aiCoachTitle: "مدرب الذكاء الاصطناعي",
    aiCoachWelcome: "مرحباً! أنا مدربك الشخصي. كيف يمكنني مساعدتك اليوم؟",
    aiCoachPlaceholder: "اكتب رسالة...",
    aiCoachSend: "إرسال",
    aiCoachError: "عذراً، حدث خطأ ما. يرجى المحاولة مرة أخرى.",
    cardAiCoach: "مدرب الذكاء الاصطناعي",
    dailyLimitReached: "تم الوصول للحد اليومي",
    dailyLimitMessage: "لقد وصلت إلى حد 20 رسالة يوميًا. حاول مرة أخرى غدًا!",
    dailyLimit: "الحد اليومي",
    buildPlanFirst: "يرجى إنشاء خطة تدريب أولاً",
    buildPlanGuidance: "أنشئ خطة التدريب الخاصة بك للوصول إلى الفئات الأخرى",
    goHome: "الصفحة الرئيسية",
    placeholder_challenge_standard: "مثال: تحدي 30 يوم",
    placeholder_challenge_numeric: "مثال: ركض 100 كم هذا الشهر",
    placeholder_challenge_habit: "مثال: 30 يوم بدون سكر",
    userProfile: "الملف الشخصي",
    profileUpdated: "تم تحديث الملف الشخصي بنجاح",
    emailReadOnly: "لا يمكن تغيير البريد الإلكتروني",
    saving: "جاري الحفظ...",
    logout: "تسجيل الخروج",
    save: "حفظ",
    dailyMotivation: "نصيحة اليوم",
    dailyTips: "نصائح يومية",
    noTipsAvailable: "لا توجد نصائح متاحة حالياً",
    readFullArticle: "اقرأ المقال كاملاً",
    readMore: "اقرأ المزيد",
  },
} as const;

type TranslationKeys = keyof Omit<typeof translations.he, "features">;
type FeatureKeys = keyof typeof translations.he.features;

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: TranslationKeys) => string;
  tf: (key: FeatureKeys) => string;
  isRtl: boolean;
  translations: typeof translations;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem("fitbarca-language");
    return (saved as Language) || "he";
  });

  const isRtl = language === "he" || language === "ar";

  useEffect(() => {
    document.documentElement.dir = isRtl ? "rtl" : "ltr";
    localStorage.setItem("fitbarca-language", language);
  }, [language, isRtl]);

  const t = (key: TranslationKeys): string => {
    const value = translations[language][key];
    if (typeof value === "string") return value;
    const fallback = translations.he[key];
    return typeof fallback === "string" ? fallback : key;
  };

  const tf = (key: FeatureKeys): string => {
    return translations[language].features[key] || translations.he.features[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, tf, isRtl, translations }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};

